spring:
  jpa:
    defer-datasource-initialization: true
  data:
    redis:
      host: 'localhost'
      port: 6379
  r2dbc:
    url: "r2dbc:postgresql://localhost:54322/"
    name: "user"
    username: "postgres"
    password: "postgres"
    pool:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
