spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:54322/"
    name: "user"
    username: "postgres"
    password: "postgres"
    pool:
      enabled: true
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
