spring:
  jpa:
    defer-datasource-initialization: true
  r2dbc:
    url: 'r2dbc:postgresql://localhost:54321/'
    name: 'record'
    username: 'postgres'
    password: 'postgres'
    pool:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
