spring:
  r2dbc:
    url: 'r2dbc:postgresql://localhost:54321/'
    name: 'postgres'
    username: 'postgres'
    password: 'postgres'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
